import DocHead from 'next/head'

export const Head = () => {
  return (
    <DocHead>
      <title>GitHub Orgs</title>
      <meta
        name="description"
        content="Generated by create next app"
      />
      <link rel="icon" href="/favicon.ico" />
    </DocHead>
  )
}
